version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./src:/var/www
      - ./logs:/var/log
    links:
      - db:db

  # db:
  #   image: mysql:5.6
  #   container_name: db
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "secret"
  #   volumes:
  #     - ./db:/var/lib/mysql

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
